### ISSUE TITLE
[API] Implement NSAPI

### ISSUE THREAD

**Issue by matthijsvdmeulen** [matthijsvdmeulen/IPMEDT4_api#14]
Daadwerkelijk de NS api implementeren volgens de research die eerder is gedaan

**Comment by matthijsvdmeulen** [comment]
Omdat uit de R&D is gebleken dat de endpoints die wij nodig hebben niet in de openbare API beschikbaar zijn, wordt alleen de passthrough in laravel geïmplementeerd, waarna bij eventuele deployment de interne API's van de NS gebruikt kunnen worden

**Comment by Charroite** [comment]
Niet mogelijk doordat er data nodig is niet in de openbare api staat.
