### ISSUE TITLE
[API] NSAPI Research

### ISSUE THREAD

**Issue by matthijsvdmeulen** [matthijsvdmeulen/IPMEDT4_api#9]
Kijken waar in de NS API je het treinnummer terug kan vinden, en waar je vervolgens moet zijn om te kijken of die trein vertraging heeft.

**Comment by Charroite** [comment]
De treinsteldata en ritnummers is niet beschikbaar in de openbare NS api. Hiervoor zou gebruik moeten worden gemaakt van de interne api van de NS.
